baseurl = "https://eliashussen.com/"
title = "Hi I am Elias"
theme = "hugo-vitae"
languagecode = "en-us"
defaultcontentlanguage = "en"


paginate = 20
canonifyurls = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true

googleAnalytics = ""
disqusShortname = ""

[params]
    author = "Elias Hussen"
    pagetitle = "Welcome"
    subtitle = "I write about Machine Learning in production; Data Warehousing and ETL pipelines; AI and data centric products; startups; books; philosophy and personal growth"

    keywords = ["ml", "machine learning", "data engineering", "data engineer", "machine learning engineer", "data science", "data scientist", "analytics", "analyst", "ai", "nlp", "big data", "nlp", "transformers", "BERT", "DistilBERT", "ehussen", "saas", "freelancer", "freelance", "data architect", "solo founder"]
    avatar = "/images/elias-tsh.jpg"
    mainSections = ["about", "posts"]

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Copyright Elias Hussen 2020"

    hidecredits = false
    hidecopyright = false 

    rtl = false

    math = true
    custom_css = ["/css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ehdev/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/ehussen/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/ehussen/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@ehussen"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "Resume"
weight = 4
url = "/resume/"

[[menu.main]]
name = "About"
url = "/about/"
weight = 5

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 6

[[menu.main]]
name = "Subscribe"
url = "/subscribe/"
weight = 7


